INSERT INTO GFT (NOME, CEP, ENDERECO, ESTADO, TELEFONE) VALUES ('GFT Alphaville', '06454-000','Alameda Rio Negro, 585', 'SP','55 11 2176-3253')
INSERT INTO GFT (NOME, CEP, ENDERECO, ESTADO, TELEFONE) VALUES ('GFT Curitiba', '80230-010', 'Av. Sete de Setembro, 2451', 'PR', '55 41 4009 5700')
INSERT INTO GFT (NOME, CEP, ENDERECO, ESTADO, TELEFONE) VALUES ('GFT Sorocaba', '18095-450', 'Av. São Francisco, 98', 'SP', '55 11 2176-3253')

INSERT  INTO TECNOLOGIA (NOME) VALUES ('Java')
INSERT  INTO TECNOLOGIA (NOME) VALUES ('SQL')
INSERT  INTO TECNOLOGIA (NOME) VALUES ('.NET')

INSERT INTO FUNCIONARIO (CARGO, INICIO_WA, MATRICULA, NOME, TERMINO_WA, GFT_ID) VALUES ('Analista de Dados', '2020/11/13', '58b', 'Sherly Holmes', '2020/11/28', 2)
INSERT INTO FUNCIONARIO (CARGO, INICIO_WA, MATRICULA, NOME, TERMINO_WA, GFT_ID) VALUES ('Desenvolvedor', '2020/11/13', '42c', 'Moriarty Jones', '2020/11/28', 1)
INSERT INTO FUNCIONARIO (CARGO, INICIO_WA, MATRICULA, NOME, TERMINO_WA, GFT_ID) VALUES ('Desenvolvedor', '2020/11/13', '31a', 'Selina K Adams', '2020/11/28', 3)

INSERT INTO FUNCIONARIO_TECNOLOGIA(FUNCIONARIO_ID, TECNOLOGIA_ID) VALUES (1,2)
INSERT INTO FUNCIONARIO_TECNOLOGIA(FUNCIONARIO_ID, TECNOLOGIA_ID) VALUES (2,1)
INSERT INTO FUNCIONARIO_TECNOLOGIA(FUNCIONARIO_ID, TECNOLOGIA_ID) VALUES (3,3)

INSERT INTO VAGA (ABERTURA_VAGA, CODIGO_VAGA, DESCRICAO_VAGA, PROJETO, QTD_VAGA) VALUES ('2020/11/13', 'e26', 'Desenvolvedor', 'Banco banco', 5)
INSERT INTO VAGA (ABERTURA_VAGA, CODIGO_VAGA, DESCRICAO_VAGA, PROJETO, QTD_VAGA) VALUES ('2020/11/13', 'z86', 'Desenvolvedor', 'Paçoca Startup', 10)
INSERT INTO VAGA (ABERTURA_VAGA, CODIGO_VAGA, DESCRICAO_VAGA, PROJETO, QTD_VAGA) VALUES ('2020/11/13', 'e26', 'Analista de Dados', 'Corretora corretora', 7)

INSERT INTO VAGA_TECNOLOGIA(VAGA_ID, TECNOLOGIA_ID) VALUES (1,2)
INSERT INTO VAGA_TECNOLOGIA(VAGA_ID, TECNOLOGIA_ID) VALUES (2,3)
INSERT INTO VAGA_TECNOLOGIA(VAGA_ID, TECNOLOGIA_ID) VALUES (3,1)